### PR TITLE
Added Error Message Box

### PR DESCRIPTION
**Pull request by eugenelet**
Informs the user that Chinese (Chewing) has to be used as input method when adding new phrase.
image

### CODE REVIEW

**Comment by david50407** [comment]
Why we have to limit the IME user used?
And in your changes, there is only popup while adding phrase failed, not about the input method.

**Comment by david50407** [comment]
Maybe all we need is show a notification to tell user `Failed to add phrase "blablabla"`, not a annoying message box.

**Comment by eugenelet** [comment]
The thing is, when I tried to add a word with other input method, it fails, and as a normal user, you won't know what happen if you didn't have a terminal to look at the warnings.

**Comment by david50407** [comment]
So why you think it failed? I can add phrase using [RIME](http://rime.im/) not chewing.

**Comment by eugenelet** [comment]
I've no idea, I've tried both BoPoMoFo and PinYin, both failed. Not really familiar with the locales, need time to look into it..

**Comment by david50407** [comment]
And some failure is about the wrong bopomofo, wrong length of bopomofo and phrase, or any other reason.
These are not about what input method you used.

**Comment by david50407** [comment]
Could you provide your environment and how to reproduce the problem in a new issue?
Maybe we have to ensure what is the real problem and get how to fix it first.

**Comment by eugenelet** [comment]
Yeah sure. But it's just a short warning. But the pop-up message box can be helpful as well. It's at least able to inform the user that the new word they added wasn't updated due to other reasons.

**Comment by Chocobo1** [comment]
You should use the status bar in the mainwindow to notify the user whether the modify/add operation is successful or not, not a pop-up window.

@david50407 
I plan to reject this, your thoughts?

**Comment by eugenelet** [comment]
@Chocobo1 I just realized that the length of the phrase input must be the same as the bopomofo input. What if the error message would be for users that uses english as input and notifying them with a warning pop-up? I think it's more of a user experience type of thing. For first time users, if it appears on the status bar if an error happens meanwhile they are testing the program by input-ing english as a test case, if they didn't notice the status bar for error message (since it's too small) they might think that it's buggy. Just my thoughts. It's okay if you reject this :)

**Comment by Chocobo1** [comment]
>Just my thoughts. 

Thanks for the feedback.

>if they didn't notice the status bar for error message (since it's too small) they might think that it's buggy

Maybe should enlarge the status text and/or add some color.

**Comment by kidwm** [comment]
Ref: #160

**Pull request closed without merging**
