### PR TITLE
Add exit in menu

### PR DESCRIPTION
**Pull request by Chocobo1**
It is de facto standard to have a "Exit" in program menu.

pic

### CODE REVIEW

**Comment by jserv** [comment]
To avoid the misunderstanding of UI tweaks, you should mention "Add file submenu" instead of "exit".

**Comment by Chocobo1** [comment]
Done.

**Comment by czchen** [comment]
Hi @Chocobo1 

I has added you as a project admin so that you can help to manage chewing-editor. Thanks for your great contributions in this project.

**Comment by Chocobo1** [comment]
@czchen 
 :smiley: Thank you! didn't expect that.

---

BTW, what about this PR? any comments?

**Pull request merged**
