### PR TITLE
Installation improvements

### PR DESCRIPTION
**Pull request by Chocobo1**
It would be best if we provided lower resolutions icons, but my DE (cinnamon) can do the downsize (256 to lower res) perfectly.
pic

### CODE REVIEW

**Comment by Chocobo1** [comment]
@jserv @czchen 
IMO, the version string should bump after merging this, because `chewing-editor.desktop` were installed to the wrong dir before this fix.

**Comment by czchen** [comment]
@Chocobo1 

I guess you mean changing version to `0.1.0`  instead of `0.0.4` ? I think this can be considered as bugfix (fix typo in `chewing-editor.desktop` install path), as well as new feature (since `chewing-editor.desktop` never works before this commit, we can consider it as a new feature). So both `0.1.0` and `0.0.4` are fine with me for the next release.

**Comment by Chocobo1** [comment]
>I guess you mean changing version to 0.1.0 instead of 0.0.4 ? 

I was thinking `0.0.4`, but `0.1.0` is fine for me too. Your decision :)

Speaking of this, I always think this program is somewhat stable & functional, *personally* I would give it a `1.0` version (in sense of a first stable release).

**Comment by czchen** [comment]
I think we can release `1.0.0` once the #2 and #108 are fixed.

**Pull request merged**
