### PR TITLE
Add Confirm window before deleting

### PR DESCRIPTION
**Pull request by YWJamesLin**
I think this is important, then I make a simple dialog. Please check my code.
Fix Issue #155

### CODE REVIEW

**Comment by david50407** [comment]
I think UNDO is enough, it seems have be discussed on google group ([link](https://groups.google.com/forum/#!topic/chewing-devel/Uml1-gyqKqw)) and the issue is opened: https://github.com/chewing/chewing-editor/issues/133

**Comment by david50407** [comment]
BTW, rebase your commit first, the merge commit shouldn't be here.

**Comment by jserv** [comment]
@YWJamesLin : please defer to the @david50407 's  suggestion to perform `rebase`.

**Comment by YWJamesLin** [comment]
Since the UNDO Function is to be implemented, this feature maybe is useless, and I directly merge my commit to master branch, I have deleted the old folked branch.
Should I open another Pull Request of this feature with `rebase` ?

**Comment by kidwm** [comment]
@YWJamesLin just create another PR.

**Pull request closed without merging**
