### PR TITLE
Change icon background to transparent

### PR DESCRIPTION
**Pull request by redfish-lee**
Inspired by dialog view of PR #120, I change icon (.svg) background to transparent.

### CODE REVIEW

**Comment by david50407** [comment]
If you want to change the icon in about dialog I made, you need to change `/rc/chewing-editor.ico` and this will also be the application icon on Windows.

**Comment by Chocobo1** [comment]
what about users who have a dark desktop wallpaper?

**Comment by david50407** [comment]
> what about users who have a dark desktop wallpaper?

Agree.
We only have black `酷` word for our icon now, maybe it can still have white border around the word, but not a white square behind it?

**Comment by redfish-lee** [comment]
I didn't consider the dark-theme users.
Thanks for advice (:

**Pull request closed without merging**
