### PR TITLE
.gitignore update

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Use `.gitignore` to ignore the targets/artifacts.

### CODE REVIEW

**Comment by Chocobo1** [comment]
I don't think enumerating all the files will be a good idea.
You should use wildcard `*` to match the files & dirs.

BTW, this all can be avoid by doing out-of-source build.

**Comment by PeterDaveHello** [comment]
> I don't think enumerating all the files will be a good idea.
> You should use wildcard * to match the files & dirs pattern.

Agree with using wildcard, I was just afraid of ignoring the files shouldn't been ignored in future.

> BTW, this all can be avoid by doing out-of-source build.

Yes, but by following the instructions in readme, the files will be in the same directory.

**Comment by czchen** [comment]
I think wildcard is better. For the file that matches wildcard rule, it can be add via `git add -f` manually, or we shall update `.gitignore`.

**Comment by PeterDaveHello** [comment]
Thanks, commit updated.

**Comment by czchen** [comment]
Thanks for contributions.

**Pull request merged**
